### ISSUE TITLE
Fußnoten im Text verlinken

### ISSUE THREAD

**Issue by waltraud-int** [sma-h/MALIS-20.3-WPM_T9_Sylvia_Hulin#1]
@sma-h: habe den Tipp von Ina und auch direkt übernommen: 

Fußnoten können aus dem Text heraus verlinkt werden. So funktioniert es:

Quelle: https://qastack.com.de/programming/25579868/how-to-add-footnotes-to-github-flavoured-markdown

**Comment by sma-h** [comment]
Hat supper geklappt. Danke für den Tipp!
