### ISSUE TITLE
Ich finde es gut!

### ISSUE THREAD

**Issue by waltraud-int** [sma-h/MALIS-20.3-WPM_T9_Sylvia_Hulin#4]
@sma-h: 
mir gefällt das sehr gut!
Das Projekt ist übersichtlich beschrieben und man bekommt einen sehr guten Eindruck davon, dass es viele kleinere Schritte hat, bei denen eine Teilautomatisierung denkbar ist. Ebenso zeigst du aber auch die Schwierigkeiten einer solchen Teilautomatisierung auf.

**Comment by sma-h** [comment]
Vielen Dank für das Feedback!
